# Travis CI configuration
# @see https://www.travis-ci.com
language: scala
scala:
  - 2.13.2

jdk:
  - openjdk11

# Code coverage integration
# @See https://codecov.io
script:
  - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)